package Inventory.Inc;
// Generated Sep 11, 2015 11:47:32 PM by Hibernate Tools 4.3.1



/**
 * StockedProductId generated by hbm2java
 */
public class StockedProductId  implements java.io.Serializable {


     private int stockId;
     private int productId;

    public StockedProductId() {
    }

    public StockedProductId(int stockId, int productId) {
       this.stockId = stockId;
       this.productId = productId;
    }
   
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockedProductId) ) return false;
		 StockedProductId castOther = ( StockedProductId ) other; 
         
		 return (this.getStockId()==castOther.getStockId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStockId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


