package Inventory.Inc;
// Generated Sep 11, 2015 11:47:32 PM by Hibernate Tools 4.3.1



/**
 * StockedProduct generated by hbm2java
 */
public class StockedProduct  implements java.io.Serializable {


     private StockedProductId id;
     private Product product;
     private Stock stock;
     private Integer amount;

    public StockedProduct() {
    }

	
    public StockedProduct(StockedProductId id, Product product, Stock stock) {
        this.id = id;
        this.product = product;
        this.stock = stock;
    }
    public StockedProduct(StockedProductId id, Product product, Stock stock, Integer amount) {
       this.id = id;
       this.product = product;
       this.stock = stock;
       this.amount = amount;
    }
   
    public StockedProductId getId() {
        return this.id;
    }
    
    public void setId(StockedProductId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }




}


